name: lint
on:
  pull_request:
  push:
    branches:
      - main
      - release-*
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - run: make generate --always-make && git diff --exit-code