name: post-prepare-please
on:
  pull_request:
jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make generate
      - run: echo "$GITHUB_REF"
      - run: cat generated
      - run: cat CHANGELOG.md
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
