name: post-prepare-please
on:
  pull_request:
jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make generate
      - run: echo "$GITHUB_REF"
      - run: cat generated
      - run: cat CHANGELOG.md
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "*: generate"
