permissions:
  actions: write
  contents: write
  checks: write
  pull-requests: write
  repository-projects: write

name: prepare-release
on:
  push:
    branches:
      - main
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm i release-please -g
          release-please release-pr --package-name=fpetkovski/release-playground \
            --repo-url=fpetkovski/release-playground \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --release-type go \
            --debug
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm i release-please -g
          release-please github-release \
            --repo-url=fpetkovski/release-playground \
            --token=${{ secrets.GITHUB_TOKEN }} \
            --release-type go \
            --debug
            