name: prepare-please-generate
on:
  push:
    branches:
    - release-v*
jobs:
  prepare-release-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version
        run: echo ${GITHUB_REF#refs/heads/} | cut -d '-' -f 2 > VERSION
      - name: Run generate
        run: make generate
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "*: generate"
