name: post-prepare-please
on:
  pull_request:
jobs:
  prepare-release-generate:
    if: "contains(github.event.pull_request.labels.*.name, 'autorelease: pending')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version
        run: echo ${GITHUB_HEAD_REF} | cut -d '-' -f 2 > VERSION
      - name: Run generate
        run: make generate
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "*: generate"
