name: post-prepare-please
on:
  pull_request:
jobs:
  prepare-release-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - name: Update version
        run: echo ${BRANCH_NAME} > VERSION
      - name: Run generate
        run: make generate
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "*: generate"
